# Generated by Django 4.1.1 on 2022-10-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
