# Generated by Django 4.1.3 on 2023-01-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_teacher_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
