# Generated by Django 4.1.3 on 2023-01-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
