# Generated by Django 4.1.1 on 2022-10-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quiz',
            new_name='exam',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='exam',
        ),
    ]
