# Generated by Django 4.1.1 on 2022-10-29 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_quiz_answer_exam_rename_quiz_question_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='exam',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question'),
            preserve_default=False,
        ),
    ]
