# Generated by Django 4.1.5 on 2023-01-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('exams', '0005_alter_examquestions_options'),
        ('questions', '0002_rename_text_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=5, verbose_name='question points'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExamQuestionAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_points', models.IntegerField(help_text='question holds how many points.')),
                ('answer_mcq', models.CharField(blank=True, max_length=100, null=True)),
                ('answer_classical', models.ImageField(blank=True, null=True, upload_to='static/images/answers_imgs')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='students.student')),
            ],
        ),
    ]
