# Generated by Django 4.1.1 on 2022-11-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_answer_exam_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassicalAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
