# Generated by Django 4.1.1 on 2022-11-11 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_classicalanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicalanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classical_answer', to='questions.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Classical Question', 'Classical Question'), ('Multiple Choice', 'MCQ')], max_length=20, null='Multiple Choice'),
            preserve_default='Multiple Choice',
        ),
    ]
