# Generated by Django 4.2.2 on 2023-06-10 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_position'),
        ('questions', '0004_examquestionanswers_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestionanswers',
            name='correct_ans',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='questions.answer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examquestionanswers',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ans', to='students.student'),
        ),
    ]
