# Generated by Django 4.2.2 on 2023-06-10 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_examquestionanswers_correct_ans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestionanswers',
            name='correct_ans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.answer'),
        ),
    ]
