# Generated by Django 4.1.1 on 2022-11-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Classical Question', 'Classical Question'), ('MCQ', 'Multiple Choice')], default='MCQ', max_length=20),
        ),
    ]
