# Generated by Django 4.1.1 on 2022-11-16 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0010_alter_coursecategory_options_alter_mcq_exam_options_and_more'),
        ('questions', '0008_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicalanswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classical_answer_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.mcq_exam'),
        ),
    ]
