# Generated by Django 4.1.3 on 2022-12-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourseenrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentcourseenrollment',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentAssignment',
        ),
        migrations.DeleteModel(
            name='StudentCourseEnrollment',
        ),
    ]
