# Generated by Django 4.1.5 on 2023-01-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/student_imgs/'),
        ),
    ]
