# Generated by Django 4.2.2 on 2023-06-11 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_examquestionanswers_correct_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestionanswers',
            name='answer_classical',
        ),
        migrations.RemoveField(
            model_name='examquestionanswers',
            name='correct_ans',
        ),
        migrations.RemoveField(
            model_name='examquestionanswers',
            name='question_points',
        ),
        migrations.AddField(
            model_name='examquestionanswers',
            name='ans_status',
            field=models.BooleanField(default=False, verbose_name='answered choice is correct or not'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examquestionanswers',
            name='answer_mcq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.answer'),
        ),
    ]
