# Generated by Django 4.1.5 on 2023-01-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='chair_imgs/'),
        ),
    ]
