# Generated by Django 4.1.3 on 2022-11-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
        ('accounts', '0003_alter_notification_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentassignment',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='studentcourseenrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentcourseenrollment',
            name='student',
        ),
        migrations.AlterField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentAssignment',
        ),
        migrations.DeleteModel(
            name='StudentCourseEnrollment',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
