# Generated by Django 4.1.5 on 2023-01-14 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100, null=True)),
                ('option2', models.CharField(max_length=100, null=True)),
                ('option3', models.CharField(max_length=100, null=True)),
                ('option4', models.CharField(max_length=100, null=True)),
                ('answer', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'MCQ Exams',
            },
        ),
        migrations.CreateModel(
            name='MCQ_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('number_of_questions', models.IntegerField()),
                ('duration', models.IntegerField(help_text='duration of the exam(in mins.)')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examss', to='teachers.course')),
            ],
            options={
                'verbose_name_plural': 'MCQ_Exams',
            },
        ),
    ]
