# Generated by Django 4.1.1 on 2022-10-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicalexam',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
