# Generated by Django 4.1.5 on 2023-01-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_course_featured_img_alter_course_student'),
        ('students', '0002_alter_student_profile_img'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_exam',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='exam_student', to='students.student'),
        ),
        migrations.AddField(
            model_name='mcq_exam',
            name='teacher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='exam_teacher', to='teachers.teacher'),
            preserve_default=False,
        ),
    ]
