# Generated by Django 4.1.1 on 2022-10-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_classicalexam_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicalexam',
            name='answer',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
