# Generated by Django 4.1.5 on 2023-01-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examquestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examquestions',
            old_name='questions',
            new_name='question',
        ),
    ]
