# Generated by Django 4.1.1 on 2022-10-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_coursecategory_alter_classicalexam_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classicalexam',
            options={'verbose_name_plural': '2. Classical Exams'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '1. Course Categories'},
        ),
    ]
