# Generated by Django 4.1.5 on 2023-03-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_examquestions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptexam',
            options={'verbose_name_plural': '2.Attempted Questions'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name_plural': '1.Exams'},
        ),
        migrations.AlterModelOptions(
            name='examquestions',
            options={'verbose_name_plural': '2.Exam Questions'},
        ),
    ]
