# Generated by Django 4.1.1 on 2022-10-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_classicalexam_options_and_more'),
    ]

    operations = [
        migrations.RenameModel("ClassicalExam","MCQExam")
    ]
