# Generated by Django 4.1.5 on 2023-04-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_attemptexam_options_alter_exam_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestions',
            name='exam',
        ),
        migrations.DeleteModel(
            name='MCQExam',
        ),
        migrations.DeleteModel(
            name='ExamQuestions',
        ),
    ]
