# Generated by Django 4.1.1 on 2022-10-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20221027_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcqexam',
            options={'verbose_name_plural': '2. MCQ Exams'},
        ),
    ]
