# Generated by Django 4.1.1 on 2022-10-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_mcqexam_option1_mcqexam_option2_mcqexam_option3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='duration of the exam')),
            ],
            options={
                'verbose_name_plural': '2. MCQ_Exams',
            },
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mcqexam',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
