# Generated by Django 4.1.1 on 2022-10-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_mcq_exam_alter_coursecategory_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='mcq_exam',
            options={'verbose_name_plural': 'MCQ_Exams'},
        ),
        migrations.AlterModelOptions(
            name='mcqexam',
            options={'verbose_name_plural': 'MCQ Exams'},
        ),
        migrations.AlterField(
            model_name='mcq_exam',
            name='time',
            field=models.IntegerField(help_text='duration of the exam(in mins.)'),
        ),
    ]
