# Generated by Django 4.1.3 on 2022-12-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_coursecategory_course_mcq_exam_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseCategory',
        ),
    ]
