# Generated by Django 4.1.3 on 2022-12-15 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_options'),
        ('exams', '0012_delete_coursecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_exam',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examss', to='teachers.course'),
        ),
    ]
