# Generated by Django 4.1.3 on 2022-12-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Teachers'},
        ),
    ]
