# Generated by Django 4.1.3 on 2023-01-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacheruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherUser',
        ),
    ]
