# Generated by Django 4.1.5 on 2023-01-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=50)),
                ('profile_img', models.ImageField(null=True, upload_to='chair_imgs/')),
            ],
            options={
                'verbose_name_plural': 'Chairman',
            },
        ),
    ]
