# Generated by Django 4.1.5 on 2023-01-16 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('results', '0001_initial'),
        ('questions', '0001_initial'),
        ('students', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MCQ_Exam',
            new_name='Exam',
        ),
        migrations.CreateModel(
            name='AttemptExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_ans', models.CharField(max_length=200, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Attempted Questions',
            },
        ),
    ]
