# Generated by Django 4.1.5 on 2023-01-17 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rename_mcq_exam_exam_attemptexam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=200)),
                ('ans1', models.CharField(max_length=200)),
                ('ans2', models.CharField(max_length=200)),
                ('ans3', models.CharField(max_length=200)),
                ('ans4', models.CharField(max_length=200)),
                ('right_ans', models.CharField(max_length=200)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
            ],
            options={
                'verbose_name_plural': '10. Exam Questions',
            },
        ),
    ]
